name: machine_learning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
-	automl 2.3.5
-	azure-ml-api-sdk 0.1.0a5
-	azure-ml-model-telemetry-api-sdk 0.1.0a7
-	biovida 0.1.1
-	costcla 0.5
-	deeplearning 0.0.1
-	django-estimators 0.2.1
-	dlib 19.4.0
-	dopaminekit 0.9.3
-	elm 0.1.1
-	epysteme 0.1.0
-	estimators 0.1.0.dev0
-	featureforge 0.1.6
-	FukuML 0.4.1
-	genetics 1.0.0
-	h2o 3.10.4.8
-	h2o_pysparkling_1.6 1.6.12
-	h2o_pysparkling_2.0 2.0.11
-	h2o_pysparkling_2.1 2.1.10
-	happyml 0.0.5
-	hep_ml 0.4.0
-	imgaug 0.2.4
-	lathe 0.2.7
-	LearningRobot 0.0.0.dev0
-	liontoolkit 0.1
-	madcore 0.6.1
-	malss 1.1.2
-	mlearn 0.0.3
-	mlpy 0.1.0
-	mlutils 0.2.0b
-	modeldb 0.0.1a7
-	Monte 0.0.11
-	moodlemlbackend 0.0.2
-	opentc 0.5.0
-	Pattern 2.6
-	pymlx 0.1.0
-	pyradigm 0.3.0.2
-	pysterior 0.1.5
-	PyZureML 1.0.5
-	qml 0.3.1
-	ramp 0.1.4
-	raredecay 1.2.1
-	rep 0.6.6
-	rlscore 0.7
-	shogun-ml 5.0.0
-	skbold 0.3.0
-	speedml 0.9.3
-	stacked_generalization 0.0.4
-	twistml 0.9
-	visualize_ML 0.2.2
-	yellowbrick 0.4.2
-	apsis 0.1.1
-	edxclassify 0.10.a1
-	empathy-machines 0.5.1
-	M-LOOP 2.1.1
-	Reinforcement-Learning-Toolkit 1.0
-	climin 0.1a1
-	common-ml 0.0.11
-	dflearn 0.1.10
-	digipy 0.1.1
-	ease 0.1.1
-	easymlpy 0.1.2
-	elm-estimator 0.0.1
-	Hebel 0.02.1
-	lmj.rbm 0.1.1
-	Lurrn 1.0.0
-	magenta 0.2.4
-	mglearn 0.1.6
-	mlimages 0.5
-	MLx 0.0.1
-	nbtransom 1.0.1
-	on_the_fly 0.02rc3
-	opentc-icap 0.5.0
-	opentc-util 0.1.5
-	optimus_ml 0.2
-	ostsa 0.1.8
-	pcSVM pre 1.0
-	percept 0.14
-	pyfms 0.2.3
-	pymut 0.1.1
-	pyrouette 0.6.0
-	pystacks 0.3
-	qtim_tools 0.1.12
-	skflow 0.1.0
-	skll 1.3
-	tictacs 0.0.3
-	Velox 0.1.0
-	waterflow v0.3
-	facefinder 0.1
-	linguistica 5.2.0
-	mazebase 0.0.1
-	pcSVMdemo 1.0
-	pescador 1.0.0
-	rlflow 0.1.3
-	tflearn 0.3.2
-	abstraction 2017.1.16.1534
-	aisnakes 1.5
-	alphapy 2.0.1
-	altify 4.2
-	am2 0.1
-	antk 0.3
-	astrodash 0.4.13
-	astroML 0.3
-	autocomplete 0.0.104
-	automata-lib 1.0.0.post4
-	azmlclient 1.0.1
-	azureml-datacollection-api 0.1.0a8
-	banditvis 0.4
-	beard 0.2
-	bnpy 0.1.5
-	bob 2.7.0
-	Braid 0.1
-	cerebrum 0.1.81
-	cesium 0.9.2
-	Cluster_Ensembles 1.16
-	cointk 0.0.11
-	Concurrent_AP 1.4
-	cortex 0.12a0
-	DBSCAN_multiplex 1.5
-	deepneuro 0.1.1
-	dltk 0.1
-	ds2sim 0.3.1
-	dsbox.overfitdetector 0.0.1
-	eatiht 0.1.14
-	ECLAIR 1.18
-	elektronn2 0.1.0
-	eli5 0.7
-	embeddings 0.0.4
-	expman 0.0.3
-	feagen 1.0.0a9
-	formasaurus 0.8
-	freediscovery 1.1.2
-	frontier 0.1.2
-	fuel 0.2.0
-	GPyOpt 1.0.3
-	hpelm 1.0.4
-	hub-toolbox 2.3.1
-	hulihutu 1.0.5
-	ibmdbpy 0.1.4
-	imbalanced-learn 0.2.1
-	infer 0.1
-	irisflower 1.0.2
-	J_box 0.1.3.2
-	kur 0.6.0
-	lspi-python 1.0.1
-	megamix 0.2
-	mempamal 0.1.5
-	metaopt 0.1.0
-	milk 0.6.1
-	milksets 0.2
-	MKLpy 0.1.3.2rc0
-	MLizard 0.1.2
-	mlpack 0.1.4
-	mlsl 0.0.1
-	mltsp 0.3.3
-	MLZ 1.2
-	mmlf 1.0
-	molml 0.6.0
-	mullpy 0.1.0
-	neupy 0.5.2
-	neural 0.1.0
-	nimfa 1.3.2
-	nlp 0.0.1
-	nn_wtf 0.1.7
-	oll 0.2.1
-	omesa 0.4.2a0
-	Optunity 1.1.1
-	orangecontrib.earth 0.1.4
-	ovostock 0.1.0
-	patent-parsing-tools 0.9.1
-	Peach 0.3.1
-	plugml 0.2.1
-	pmlb 0.2
-	pmll 0.2.2
-	prettytensor 0.7.4
-	pug-invest 0.0.18
-	py_pcha 0.1.2
-	PyAI 2.12
-	PyBrain2 0.4.0
-	pydatalearn 0.1.3
-	pydeeptoy 1.0.0.7
-	pyimpute 0.1.2
-	pymadlib 0.1.7
-	pymldb 0.8.1
-	pymltk 0.1
-	pyrallel 0.2.1
-	pysgd 0.0.1a2
-	pytrain 0.0.12
-	redditnlp 0.1.3
-	redten 1.0.1
-	rgf_python 1.3.1
-	sanctuary 0.1.2
-	ScaleHD 0.247
-	scikit-learn 0.18.2
-	scikit-learn_runnr 0.18.dev1
-	scikits.learn 0.8.1
-	skdata 0.0.4
-	sklearn-extensions 0.0.2
-	smqtk 0.6.3.dev1
-	spark-sklearn 0.2.0
-	stacking 0.1.3
-	syn.learn 0.0.1
-	systemml 0.14.0
-	tensorflowonspark 1.0.0
-	tensorfx 0.1.3
-	theanets 0.7.3
-	thinc 6.7.3
-	tictactoe_learn 0.0.1
-	tidml 0.1.4
-	tradingmachine 0.1.7
-	tweet-preprocessor 0.5.0
-	upsilon 1.2.6
-	votedperceptron 1.0.0
-	vowpalwabbit 8.3.2
-	vsmrfs 0.9.0
-	vtt 0.3.1
-	wabbit_wappa 0.3.0
-	wechinelearn 0.0.1
-	wise 0.9.8
-	Wordbatch 1.2.0b0
-	xbob.paper.tpami2013 1.0.0
-	xcessiv 0.5.0
-	xcs 1.0.0
-	acton 0.3.3
-	bayesredis 1.2.1
-	Boruta 0.1.5
-	category_encoders 1.2.3
-	classipy 1.1.1
-	crowdastro 0.1.1
-	empythy 1.0.0
-	evostra 1.0.1
-	gradient-optimizers 0.0.4
-	kohonen 1.1.2
-	langdist 0.4.1
-	liquidSVM 1.0.1
-	lmj.pursuit 0.3.1
-	MDP 3.5
-	mlens 0.1.3
-	mltool 0.6
-	neurolab 0.3.5
-	perceptron 1.1.0
-	pyaixi 1.0.4
-	pydnn 0.0.dev
-	pyfora 0.5.10
-	python-weka-wrapper 0.3.10
-	python-weka-wrapper3 0.1.2
-	ReliefF 0.1.2
-	RLToolkit 1.0
-	sklearn-gbmi 1.0.0
-	synapy 0.1
-	abu-quant 0.0.1
-	abupy 0.0.8
-	abuQuant 0.0.1
-	aima 2015.4.5
-	apgl 0.8.1
-	arachnid 0.1.7
-	auto-sklearn 0.2.0
-	autocolorize 0.2.1
-	Azimuth 2.0
-	azureml 0.2.7
-	azuremlcli 0.2rc427
-	badfish 0.1.2
-	balu 0.1.16
-	bat-country 0.2
-	becca 0.9.0
-	benderthon 0.1.1
-	biased-stop-words 2017.5.13.4
-	bleedml 0.0.7
-	bob.learn.em 2.0.13
-	bob.learn.linear 2.1.1
-	botkit 0.1
-	buluml 0.0.1
-	casket 0.0.8a0
-	catprep 0.0.4
-	causalmodels 0.4.0
-	CGvsPhoto 0.0.2
-	chakin 0.0.6
-	change-finder 0.0.1
-	char-classifer 0.6.0
-	chat 1.0.5.dev58
-	chazutsu 0.5.3
-	chClassifier 0.6.4
-	chicksexer 0.1.6
-	cloudbiolinux 0.3a
-	cloudml 0.4.2
-	cognious 1.1
-	conclas 0.1.2
-	condor-kmeans 0.9
-	cox-nnet 0.202
-	crbm 0.1
-	cribbage 0.1.0
-	cudnn-python-wrappers 2.0b2
-	customlogging 0.1.10
-	dataget 0.1.11
-	dataloader 2.0
-	dbcollection 0.1.4
-	dcgpy 1.0.1
-	decision_tree 0.04
-	destimator 0.1.4
-	discomll 0.1.4.2
-	DistanceClassifier 0.0.8
-	doc2text 0.2.4
-	dock 0.0.1
-	drago 0.2.3
-	ds-lime 0.1.1.21
-	DSPP-Keras 0.0.5
-	dtit 1.0.2
-	dummybear 0.0.1
-	dvc 0.8.6
-	dvd 0.1.3
-	easymlserver 0.1.2
-	Edward 1.3.3
-	eighbit 0.1
-	elaspic 0.1.39
-	elektronn 1.0.14
-	ENN 0.14
-	ensembles 0.1.5
-	estnltk-textclassifier 1.2.2
-	explain_sklearn 0.0.2
-	ezcluster 0.0.3
-	fabia 2016.8
-	fcl 0.0.9
-	fcn 6.0.3
-	fdep 0.2.5
-	featureimpact 1.1.0
-	featuretools 0.1.2
-	ffx 1.3.6
-	gate 0.0.4
-	gbdt 0.3.1.2
-	genalg 1.0.3
-	GeosPy 0.1.4
-	glove 1.0.0
-	glowfi.sh 0.3.51
-	GmdhPy 0.1.1a0
-	GPy 1.7.7
-	GraphLab-Create 2.1
-	graphs 0.1.2
-	gym-starter-kit 0.0.3
-	hagelslag 0.2
-	healthcareai 0.1.8
-	hng 0.3
-	hydrat 0.9.5
-	hyperspy 1.3
-	image_featurizer 0.4.2
-	imblearn 0.0
-	iml 0.2.5
-	IndicoIo 1.0.9
-	insults 0.1.12
-	ionmf 1.1
-	JDRA 0.0.1
-	jubatus 1.0.0.post1
-	Juboor_Toolbox 0.1.3.1
-	kaggle_tools 0.0.2
-	kemlglearn 0.3.6
-	keras_elastic_callback 0.1
-	kHLL 0.0.4
-	km3learn 0.1.0
-	kmc2 0.1
-	knor 0.0.1a10
-	krakenous 0.3
-	ksvd 0.0.3
-	landmark_ml 0.1.1
-	lca_metrics 0.1.0
-	lcc 1.1.8
-	libextract 0.0.12
-	lime 0.1.1.22
-	lmj.particle 0.1.1
-	lmj.perceptron 0.1.1
-	lmj.tagger 0.1.1
-	logistic 0.1.0
-	lsanomaly 0.1.3
-	lumidatumclient 0.10.5
-	lykability 1.0.0
-	mab 0.1.24
-	majorityvoting 0.1.5
-	mang 0.1.3.2
-	MarkovEquClasses 1.0.1
-	mcfly 1.0.1
-	meteos 0.0.0
-	minica 0.0.1
-	MiniSom 1.1
-	minitrace 0.2
-	ml 0.0.0
-	ml-lib 0.0.3
-	ml-toolkit 0.07
-	ml_metrics 0.1.4
-	mlboost 0.4.1
-	MLDateTimeParser 0.0.0
-	mlfromscratch 0.0.4
-	mlpods 0.1
-	mlPyUtils 0.1
-	mlstatpy 0.1.200
-	mltk 0.0.5
-	mlutility 0.1.1
-	mlxtend 0.7.0
-	mmbot 1.0.9
-	modlamp 3.2.1
-	mondrianforest 0.0.2
-	monkeylearn 0.3.7
-	moodleinspire 0.0.9
-	mooncake_utils 0.2
-	musicmood 0.1.2
-	NaiveBayes 1.0.0
-	neokami-sdk 0.2
-	nervananeon 0.8.1
-	NetBuilder 0.2.2
-	netception 0.2.0
-	neuralcli 1.6
-	nlup 0.5
-	nnabla 0.9.1rc3
-	nnabla_ext-cuda 0.9.1rc3
-	nnet-ts 1.0
-	nonconformist 2.1.0
-	nutsml 1.0.27
-	openfst 1.6.1
-	Orange 2.7.8
-	Orange-ModelMaps 0.2.8
-	Orange-Multitarget 0.9.3
-	Orange-NMF 0.1.2
-	Orange-Reliability 0.2.14
-	Orange-Text 1.2a1
-	Orange3 3.4.4
-	Orange3-Network 1.2.0
-	othello 1.0b1
-	pandas-summary 0.0.41
-	ParallelDots 0.9.1
-	paramz 0.7.4
-	phased-lstm-keras 1.0.2
-	pic2vec 0.5.0
-	polyssifier 0.5.1
-	practnlptools 1.0
-	predictiveanalytics 0.0.4
-	prox_tv 3.2.1
-	pti-analyzer 0.0.19
-	pug 0.1.22
-	pug-ann 0.0.22
-	py-enigma 0.1
-	py-sam 0.1
-	pybolt 0.1.4
-	PyBrain 0.3.3
-	pyconclas 0.1.2
-	pydepr 0.14
-	pyflux 0.4.15
-	pygam 0.2.17
-	pygfl 1.0.2
-	pyglyph 0.3.2
-	pyGPGO 0.1.0.dev1
-	pymanopt 0.2.2
-	PyMissingData 1.1.2
-	pymyra 1.0.5
-	pyndl 0.3.0
-	PyNomaly 0.1.4
-	pyoxford 0.4.0
-	pyrm114 0.62
-	PySCUBA 0.1.1
-	pyspeakrec 0.1.0
-	PyStanfordDependencies 0.3.1
-	PyTLDR 0.1.4
-	pytreebank 0.2.4
-	pywikilinks 0.0.2
-	pyxval 0.9.3
-	quantgov 0.2.1
-	relevancer 0.1.0a1
-	reportbot 0.1
-	rlstm 0.2.46
-	rusentiment 0.0.3
-	Savitzky-Golay-Filters 1.0
-	scnn 1.3.1
-	shap 0.2.4
-	sharky 0.1
-	simab 0.1.36
-	siml 0.1.2.1
-	simple_ml 0.1.1
-	sklearn 0.0
-	sklearn_extras 0.1.1
-	smac 0.5.0
-	smoothfdr 0.9.4
-	sockeye 1.0.3
-	solidpy 0.1
-	somber 1.1.0
-	sompy 0.1.1
-	sopython-nidaba 0.1.0.dev0
-	spammy 1.0.3
-	spark-ml-streaming 0.1.0
-	spca 1.2.0
-	stanza 0.3
-	stolos 2.0.1
-	syntaxnet 0.2
-	syntaxnet-with-tensorflow 0.2
-	tableh 0.0.01
-	tensor2tensor 1.0.12
-	tensorbase 0.3
-	tensorflow 1.2.1
-	tensorflow-gpu 1.2.1
-	tensorflow-tensorboard 0.1.2
-	tensorspark 1.0.6
-	test_helper 0.2
-	tf-sdp 0.9
-	tfgraphviz 0.0.6
-	TheanoLM 1.2.0
-	thyro 0.1.0a3
-	topycal 0.1.1
-	tslearn 0.0.25
-	tytan 0.0.1
-	vecstack 0.1
-	visioncpp 0.1.0
-	vizdoom 1.1.2
-	vocab 0.0.2
-	vowpal_porpoise 0.3
-	vptree 1.0.2
-	ward-metrics 0.9.2
-	weles 0.4.3
-	wordgrapher 0.3.1
-	wpd 1.0
-	xgbfir 0.2
-	yadll 0.0.1
-	yard 0.2.4
-	yftest 1.0.0
-	z-ml-utils 0.1
-	zChainer 0.3.2
-	ztilde 0.4
-	dragonfire 0.9.4
-	tgym 0.1.14
-	abed 0.0.3
-	ActionML 0.0.10
-	ad3 2.0.2
-	adenine 0.1.4
-	alchemyapi_python 1.2.1
-	analyzefit 0.3.4
-	annoy 1.9.1
-	ansible 2.3.1.0
-	antispam 0.0.10
-	antispoofing.clientspec 1.0.3
-	antispoofing.competition_icb2013 1.1.0
-	antispoofing.crossdatabase 1.0.1
-	antispoofing.dog 1.0.2
-	antispoofing.evaluation 2.0.5
-	antispoofing.eyeblink 1.0.4
-	antispoofing.fusion 2.0.1
-	antispoofing.fusion_faceverif 3.0.2
-	antispoofing.lbp 2.0.4
-	antispoofing.lbptop 2.0.3
-	antispoofing.motion 2.0.3
-	antispoofing.optflow 2.0.0
-	antispoofing.utils 2.0.7
-	antispoofing.verification.gmm 1.0.2
-	artemis-ml 1.4
-	astroML_addons 0.2.2
-	audiodatasets 1.0.0
-	autolux 0.0.30
-	autopager 0.2
-	bayespy 0.5.8
-	bdot 0.1.7
-	bdss-client 1.0.1b2
-	bebop.protocol 0.1
-	bigml 4.10.4
-	bigmler 3.11.2
-	BlackBoxAuditing 0.0.2
-	bob.ap 2.1.4
-	bob.bio.base 3.1.2
-	bob.bio.caffe_face 1.0.0
-	bob.bio.csu 2.0.4
-	bob.bio.face 3.2.0
-	bob.bio.gmm 3.0.2
-	bob.bio.pericrosseye_competition 1.0.2
-	bob.bio.spear 3.1.0
-	bob.bio.video 3.2.0
-	bob.blitz 2.0.13
-	bob.buildout 2.1.2
-	bob.core 2.1.8
-	bob.db.arface 2.1.3
-	bob.db.asvspoof 1.1.6
-	bob.db.asvspoof2017 1.0.2
-	bob.db.atnt 2.0.9
-	bob.db.atvskeystroke 2.1.4
-	bob.db.avspoof 2.2.7
-	bob.db.banca 2.1.4
-	bob.db.base 2.3.1
-	bob.db.bio_filelist 2.1.1
-	bob.db.biosecure 2.1.4
-	bob.db.biosecurid.face 2.1.7
-	bob.db.casme2 2.1.4
-	bob.db.caspeal 2.1.4
-	bob.db.cohface 1.0.3
-	bob.db.cuhk_cufs 2.1.3
-	bob.db.frgc 2.1.2
-	bob.db.gbu 2.1.3
-	bob.db.hci_tagging 1.0.3
-	bob.db.ijba 2.0.2
-	bob.db.iris 2.1.0
-	bob.db.kboc16 2.0.10
-	bob.db.lfw 2.1.4
-	bob.db.livdet2013 2.0.5
-	bob.db.mnist 2.1.0
-	bob.db.mobio 2.1.4
-	bob.db.msu_mfsd_mod 2.2.1
-	bob.db.multipie 2.1.3
-	bob.db.nist_sre12 3.0.2
-	bob.db.putvein 1.2.0
-	bob.db.replay 3.0.2
-	bob.db.replaymobile 1.1.2
-	bob.db.scface 2.1.3
-	bob.db.utfvp 2.3.6
-	bob.db.voicepa 1.0.1
-	bob.db.voxforge 2.1.3
-	bob.db.wine 2.0.8
-	bob.db.xm2vts 2.1.3
-	bob.db.youtube 2.1.3
-	bob.extension 2.4.2
-	bob.io.audio 2.0.5
-	bob.io.base 2.1.0
-	bob.io.image 2.2.2
-	bob.io.matlab 2.0.9
-	bob.io.video 2.0.15
-	bob.ip.base 2.0.15
-	bob.ip.color 2.0.9
-	bob.ip.draw 2.0.8
-	bob.ip.facedetect 2.1.3
-	bob.ip.facelandmarks 1.0.4
-	bob.ip.flandmark 2.1.5
-	bob.ip.gabor 2.0.10
-	bob.ip.optflow.hornschunck 2.0.12
-	bob.ip.optflow.liu 2.0.11
-	bob.ip.skincolorfilter 0.0.3
-	bob.kaldi 1.0.5
-	bob.learn.activation 2.0.9
-	bob.learn.boosting 2.0.12
-	bob.learn.libsvm 2.0.12
-	bob.learn.mlp 2.1.5
-	bob.math 2.1.1
-	bob.measure 2.4.0
-	bob.pad.base 1.0.8
-	bob.pad.voice 1.0.4
-	bob.palmvein 2.0.0a1
-	bob.paper.CVPRW_2016 1.0.2
-	bob.paper.ICB2015 2.0.0a0
-	bob.paper.taslp_2016 1.0.3
-	bob.sp 2.0.9
-	bob.thesis.ichingo2015 0.0.1
-	boto 2.48.0
-	boto-mws 2.46.2
-	boto-patch 2.38.0
-	bquery 0.2.10
-	brothon 0.2.2
-	bt 0.2.5
-	caerbannog 0.1
-	ccsnmultivar 0.0.5
-	cec2013lsgo 0.1
-	challenge.uccs 1.0.2
-	ChatterBot 0.7.0
-	ck 1.9.1
-	claw 1.3.0
-	clipper_admin 0.1.4
-	clusteror 0.0.2
-	collate 0.2.0
-	constractor 0.1.0
-	coremltools 0.4.0
-	cosmic_ray 1.1.0a1
-	cosmoabc 1.0.5
-	cotede 0.19.1
-	coursera 0.5.2
-	coursera-dl 0.9.0
-	courseraresearchexports 0.0.24
-	crumb 0.0.0a
-	ctdl 1.5.0
-	cubicweb-semnews 0.2.0
-	cytoflow 0.5.2
-	datagami-python 0.0.5
-	datapot 0.1.3
-	deap 1.0.2
-	dedupe 1.7.0
-	DEICODE 1.1.2
-	Density_Sampling 1.3
-	dicttokv 0.1.5
-	distributions 2.1.0
-	django-analyze 0.4.23
-	djangolearn 0.1
-	DocumentFeatureSelection 1.3.5
-	dollarpy 0.1.1
-	dragnet 1.1.0
-	dsegmenter 0.2.12
-	dstoolbox 0.5.7
-	dukedeploy 0.1.5
-	emailage-official 1.0.1
-	enlopy 0.1.dev7
-	epitopes 0.3.2
-	estimate.gender 0.4
-	evogrid 0.1.0
-	experimentator 0.3.1
-	experimenter 0.1.6
-	face_recognition 0.2.0
-	facereclib 2.1.2
-	fairml 0.1.1.5rc8
-	fastFM 0.2.9
-	FATS 1.3.6
-	fms 0.1.9
-	FoLiA-tools 1.4.1.54
-	fuzzy_dempster_shafer 0.13
-	github-dl 0.1a9
-	google-cloud-language 0.25.0
-	google-cloud-natural-language 0.24.0
-	google-cloud-videointelligence 0.25.0
-	google-cloud-vision 0.25.0
-	gplearn 0.2
-	graphkit 1.0.3
-	gridtk 1.4.4
-	gsh 0.12.4
-	GutenbergPy 0.2.0
-	halcon 0.0.21
-	hashedindex 0.4.0
-	hcpre 0.5.5
-	hdidx 0.2.8.2
-	HeyAthena 1.3.2
-	hoggorm 0.9.0
-	hotword_detection 1.2
-	html_text 0.2.1
-	hwit-examples 0.01-r00018
-	infpy 0.4.13
-	intuition 0.4.3
-	invenio-classifier 1.3.1
-	invoice2data 0.2.59
-	irlib 0.1.1
-	Kaggler 0.5.2
-	keras-tqdm 2.0.1
-	kernel_tuner 0.1.4
-	Kotti 1.3.0
-	labelImg 1.3.4.0
-	lachesis 0.0.3.0
-	liac-arff 2.1.1
-	Lifetimes 0.8.0.0
-	luigi 2.6.2
-	madmom 0.15.1
-	maskattack.lbp 1.0.4
-	maskattack.study 1.0.0
-	matminer 0.1.0
-	MD-ELM 0.61
-	metaheuristic-algorithms-python 0.1.6
-	mhcflurry 0.9.0
-	midi2audio 0.1.1
-	ml-insights 0.0.15
-	mldatalib 0.2.1
-	mljar 0.0.6
-	mltoolkit 0.1.0
-	mozsci 0.9.2
-	mrec 0.3.0
-	mtm_stats 0.4.4.1
-	neuropredict 0.2.4.5
-	nipype 0.13.1
-	nolearn 0.6.0
-	nupic 1.0.0
-	Omnivore 0.13.7
-	opensubmit-web 0.6.3
-	Orange3-Educational 0.1.0
-	osprey 1.1.0
-	palladio 2.0.3rc1
-	palladium 1.1.0.1
-	pattern3 3.0.0
-	pave 0.69
-	pcalg 0.1.5
-	pdfrename 0.1
-	pdpipe 0.0.5
-	pdtrend 0.2.3
-	pepdata 0.7.0
-	pipefitter 1.0.0
-	plone.testing 5.1.1
-	POT 0.3
-	ppsqlviz 1.0.1
-	PredictionIO 0.9.8
-	propagate 0.2.1
-	provenance 0.10.0
-	pug-data 0.0.4
-	py-mcmc 0.0a1
-	py_entitymatching 0.1.0
-	pya3rt 1.1
-	PyAgg 0.2.0
-	pyarm 1.1.dev1
-	pyautoweka 1.1
-	pybullet 1.2.1
-	pyCroscopy 0.0a50
-	pycv 0.2.2
-	pydriver 1.0.1
-	pyelt 0.9.4.6a0
-	PyFunctional 1.0.0
-	pyGPs 1.3.5
-	pyhacrf 0.1.2
-	pyhacrf-datamade 0.2.1
-	PyLMNN 1.5.2
-	pylstar 0.1.1
-	pymus 0.2.5
-	pypot 3.0.3
-	pypoticia 3.0.3
-	pypyraws 0.0.4
-	PyRATA 0.3.2
-	pyswmm 0.3.4
-	pytextrank 1.1.0
-	python-rdm 0.1.8a
-	pytosca 0.2.1
-	pytreecat 0.1.5
-	PyWeka 0.5dev
-	pywerview 0.2.0
-	regex4dummies 1.4.6
-	revscoring 1.3.15
-	rifmator_engine 1.0
-	robotreviewer 0.0.4
-	root_numpy 4.7.2
-	rrbob 1.0
-	sacred 0.7.0
-	sapl 1.0.1
-	sapreprocessor 1.0.17
-	ScalaFunctional 0.6.0
-	SCFGP 0.1.0
-	scikit-gpuppy 0.9.3
-	scikit-plot 0.2.7
-	scikit-survival 0.2
-	scikit-viz 0.1
-	scripnix 0.1.12
-	simple-opencv-ocr 0.0
-	simpleai 0.8
-	skeleprint_ui 1.16
-	skggm 0.2.6
-	skl-groups 0.1.7
-	skl-groups-accel 0.1.6
-	sklearn-pandas 1.5.0
-	snake_nupic 0.0.2.dev0
-	spark-yarn-submit 1.0.0
-	sparse 0.1.0
-	spear.nist_sre12 1.0.0
-	spherecluster 0.1.2
-	sputnik 0.9.3
-	sshconfig 1.0
-	storlever 0.1.2
-	storm 0.20
-	strum 0.0
-	swk 0.0.4a18
-	tabtool 0.2.0
-	tabtools 0.3.3
-	talon 1.4.1
-	tfmesos 0.0.4
-	tfr 0.2.2
-	tfyarn 0.0.3.dev3
-	TimeSide 0.8
-	tinytools 1.0.6
-	titanium 0.0.1
-	TPOT 0.8.3
-	trustedanalytics 0.8.0.dev20160928710
-	tsfresh 0.8.1
-	universe 0.21.3
-	vf-portalytics 0.1.2
-	waterworks 0.2.5
-	wide-product 0.0.1
-	workspacemanager 0.1.12
-	xblock-openedx 0.4.1
-	xbob.buildout 1.0.4
-	xbob.daq 1.0.6
-	xbob.db.nist_sre12 1.2.0
-	xbob.db.utfvp 2.0.0
-	xbob.db.voxforge 0.1.0
-	xbob.fingervein 1.0.0
-	xbob.flandmark 1.1.0
-	xbob.optflow.liu 1.1.2
-	xbob.paper.BIOSIG2014 1.0.0
-	xbob.paper.BTFS2013 1.0.1
-	xbob.paper.example 0.2.0
-	xbob.paper.jmlr2013 0.2.0
-	xbob.thesis.elshafey2014 0.0.1a0
-	xfacereclib.extension.CSU 2.0.0
-	xfacereclib.paper.IET2014 1.0.0
-	xframes 0.3.7
-	yarntf 0.0.3.dev3
-	z3gi 0.1.1
